# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-11 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jms_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact Request',
                'verbose_name_plural': 'Enquiries',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='lorem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_request', to='jms_site.Service'),
        ),
    ]
