# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-11 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jms_site', '0002_auto_20190611_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='wetga', upload_to='services'),
            preserve_default=False,
        ),
    ]
