# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-16 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jms_site', '0004_auto_20190615_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About Information',
            },
        ),
    ]
