# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-16 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jms_site', '0008_auto_20190616_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialBlurb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blurb', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Blurb',
                'verbose_name_plural': 'Blurb',
            },
        ),
    ]
