# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-16 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jms_site', '0009_testimonialblurb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestimonialBlurb',
        ),
    ]
