# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-18 15:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jms_site', '0011_jobpost_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 18, 15, 55, 49, 421243, tzinfo=utc), editable=False),
        ),
    ]
