# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-19 13:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jms_site', '0012_testimonials_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='meta',
            field=models.TextField(default='12e12e'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 19, 13, 4, 21, 615097, tzinfo=utc), editable=False),
        ),
    ]
