# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-19 13:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jms_site', '0013_auto_20190619_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='testimonial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jms_site.Testimonials'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 19, 13, 29, 5, 150731, tzinfo=utc), editable=False),
        ),
    ]
