# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-20 15:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jms_site', '0014_auto_20190619_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBlurb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Service Blurb',
                'verbose_name_plural': 'Service Blurbs',
            },
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 20, 15, 10, 44, 294507, tzinfo=utc), editable=False),
        ),
    ]
