# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-22 12:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jms_site', '0017_auto_20190620_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='brief',
            field=tinymce.models.HTMLField(default='wegweg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 22, 12, 22, 8, 580053, tzinfo=utc), editable=False),
        ),
    ]
