# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-22 12:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jms_site', '0018_auto_20190622_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 22, 12, 27, 51, 174084, tzinfo=utc), editable=False),
        ),
    ]
