# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-22 13:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jms_site', '0019_auto_20190622_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description_active',
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 22, 13, 49, 54, 93941, tzinfo=utc), editable=False),
        ),
    ]
