# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-21 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jms_site', '0021_auto_20190710_1803'),
        ('jms_site', '0021_auto_20190710_1518'),
    ]

    operations = [
    ]
