# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-21 16:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jms_site', '0022_merge_20190721_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='popular',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 21, 16, 14, 36, 381767, tzinfo=utc), editable=False),
        ),
    ]
