# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-21 17:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jms_site', '0023_auto_20190721_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 21, 17, 34, 43, 2282, tzinfo=utc), editable=False),
        ),
    ]
